name: Build Centos7 Releases

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build-snapshot:
    name: Build Snapshot
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        sparkver: [ spark-3.3]
        scalaver: [ 2.12 ]
        auronver: [5.0.0]
        celebornver: [0.5]
        exclude:
          # Only build on scala-2.13 for spark-3.5
          - sparkver: spark-3.0
            scalaver: '2.13'
          - sparkver: spark-3.1
            scalaver: '2.13'
          - sparkver: spark-3.2
            scalaver: '2.13'
          - sparkver: spark-3.3
            scalaver: '2.13'
          - sparkver: spark-3.4
            scalaver: '2.13'

    steps:
      - uses: actions/checkout@v4
      - uses: s4u/setup-maven-action@main
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: prompt/actions-commit-hash@v3
        id: commit

      - name: Detect osclassfier
        id: detect-osclassfier
        run: |
          osclassfier=$(./build/mvn help:evaluate -Dexpression=os.detected.classifier -q -DforceStdout -P${{ matrix.sparkver }})
          echo "osclassfier=$osclassfier" >> $GITHUB_ENV

      - name: Cache auron-${{ matrix.sparkver }}_${{ matrix.scalaver }}
        id: cache
        uses: actions/cache@v3
        with:
          path: target-docker/auron-${{matrix.sparkver}}_${{matrix.scalaver}}-release-${{ env.osclassfier }}-${{ matrix.auronver }}-SNAPSHOT.jar
          key: auron-${{matrix.sparkver}}_${{matrix.scalaver}}-release-${{ env.osclassfier }}-${{ matrix.auronver }}-SNAPSHOT.jar

      - uses: ScribeMD/rootless-docker@0.2.2
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: ScribeMD/docker-cache@0.5.0
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          key: docker-centos7-${{ hashFiles('dev/docker-build/centos7/Dockerfile') }}

      - name: Build auron-${{ matrix.sparkver }}_${{ matrix.scalaver }}
        run: |
          sed -i 's/docker-compose -f/docker compose -f/g' ./release-docker.sh
          SHIM=${{ matrix.sparkver }} MODE=release SCALA_VERSION=${{ matrix.scalaver }} CELEBORN_VERSION=${{ matrix.celebornver }} ./release-docker.sh

      - name: Upload auron-${{ matrix.sparkver }}_${{ matrix.scalaver }}
        uses: actions/upload-artifact@v4
        with:
          name: auron-${{matrix.sparkver}}_${{matrix.scalaver}}-release-${{ env.osclassfier }}-${{ matrix.auronver }}-SNAPSHOT-ce7-${{ steps.commit.outputs.short }}.jar
          path: target-docker/auron-${{matrix.sparkver}}_${{matrix.scalaver}}-release-${{ env.osclassfier }}-${{ matrix.auronver }}-SNAPSHOT.jar
          overwrite: true
